services:
  postgres:
    image: postgres:17
    container_name: salim_postgres
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: pm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    container_name: salim_app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: gorm
      DB_PASSWORD: 12345678
      DB_NAME: pm
      DB_SSL: disable
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  migrate:
      image: migrate/migrate
      command: [
        "-path", "/migrations",
        "-database", "postgres://gorm:12345678@postgres:5432/pm?sslmode=disable",
        "up"
      ]
      volumes:
        - ./migrations:/migrations
      depends_on:
        - postgres

volumes:
  pgdata: